# Generated by Django 5.1 on 2024-08-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_cliente_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, default='comprobantes/comprobante-default.jpg', null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/producto-default.jpg', null=True, upload_to='productos/'),
        ),
    ]
