# Generated by Django 5.1 on 2024-09-05 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_detalle_pedido_alter_destinatario_ciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/producto-default.jpg', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/producto-default.jpg', null=True, upload_to='items/'),
        ),
    ]
