# Generated by Django 5.1 on 2024-08-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopersonalizado',
            name='personalizacion',
        ),
        migrations.RemoveField(
            model_name='productopersonalizado',
            name='producto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_pedido',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='personalizaciones_aplicadas',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('carrito', 'Carrito')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='pedidos.destinatario'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='pedidos.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='items/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('base', 'Producto Base'), ('extra', 'Personalización')], max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Personalizacion',
        ),
        migrations.DeleteModel(
            name='ProductoPersonalizado',
        ),
    ]
