# Generated by Django 5.1 on 2024-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_destinatario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('principal', 'Principal'), ('alternativo', 'Alternativo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('validando', 'Validando')], default='validando', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('deposito', 'Deposito')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'Carrito'), ('desarrollando', 'En desarrollo'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='Carrito', max_length=15),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='tipo',
            field=models.CharField(choices=[('principal', 'Principal'), ('alternativo', 'Alternativo')], max_length=50),
        ),
    ]
