# Generated by Django 5.1 on 2024-08-14 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_item_imagen_alter_pago_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.producto'),
        ),
    ]
