# Generated by Django 5.1 on 2024-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_item_tipo_alter_pago_estado_alter_pago_metodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'Carrito'), ('validando', 'Validando pago'), ('desarrollando', 'En desarrollo'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='Carrito', max_length=15),
        ),
    ]
