# Generated by Django 5.1 on 2024-09-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'Carrito'), ('verificando', 'Validando pago'), ('desarrollando', 'En desarrollo'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='Carrito', max_length=15),
        ),
    ]
