# Generated by Django 5.1 on 2024-08-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_detalle_alter_item_producto_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='pedidos.destinatario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
